#!/bin/sh

#### THE SPOOL DIR IS "SPOOLDIR" IN THE LINE BELOW ####

wwwoffle_spool=SPOOLDIR

####

cd $wwwoffle_spool

# Set the path to include the namazu.cgi executable

PATH=$PATH:/usr/local/bin
PATH=$PATH:/usr/local/cgi-bin
PATH=$PATH:/usr/local/libexec
PATH=$PATH:/usr/lib/cgi-bin    # The Debian location
PATH=$PATH:/opt/www/cgi-bin    # The Suse location
export PATH

# Do the searching

NAMAZURC=search/namazu/conf/namazurc
export NAMAZURC

namazu.cgi
