#!/bin/sh

#### THE SPOOL DIR IS "/var/cache/wwwoffle" IN THE LINE BELOW ####

wwwoffle_spool=/var/cache/wwwoffle

####

cd $wwwoffle_spool

# Set the temporary directory used for merging

#TMPDIR=/tmp
TMPDIR=search/htdig/tmp
export TMPDIR

# Set up a log file.

exec >> /var/log/wwwoffle-htdig.log 2>&1

date "+%n+%Y-%m-%d %H:%M wwwoffle-htdig-lasttime"

# Do the digging and merging

htdig -i -c search/htdig/conf/htdig-lasttime.conf

htmerge -m search/htdig/conf/htdig-lasttime.conf \
    -c search/htdig/conf/htmerge.conf
