#!/bin/sh

#### THE SPOOL DIR IS "/var/cache/wwwoffle" IN THE LINE BELOW ####

wwwoffle_spool=/var/cache/wwwoffle

####

cd $wwwoffle_spool

# Set the temporary directory used for creating the fuzzy endings

#TMPDIR=/tmp
TMPDIR=search/htdig/tmp
export TMPDIR

# Set up a log file.

exec >> /var/log/wwwoffle-htdig.log 2>&1

# Create the fuzzy databases

htfuzzy -c search/htdig/conf/htfuzzy.conf endings

htfuzzy -c search/htdig/conf/htfuzzy.conf synonyms
