#!/bin/sh

#### THE SPOOL DIR IS "/var/cache/wwwoffle" IN THE LINE BELOW ####

wwwoffle_spool=/var/cache/wwwoffle

####

cd $wwwoffle_spool

# Do the searching

CONFIG_DIR=$wwwoffle_spool/search/htdig/conf
export CONFIG_DIR

unset REQUEST_METHOD
exec /usr/lib/cgi-bin/htsearch -c $CONFIG_DIR/htsearch.conf $QUERY_STRING
echo "Cannot run htsearch"
exit 1
