#!/bin/sh

#### THE SPOOL DIR IS "SPOOLDIR" IN THE LINE BELOW ####

wwwoffle_spool=SPOOLDIR

####

cd $wwwoffle_spool

# Set the path to include the htsearch executable

PATH=$PATH:/usr/local/bin
PATH=$PATH:/usr/local/cgi-bin
PATH=$PATH:/usr/local/libexec
PATH=$PATH:/usr/lib/cgi-bin    # The Debian location
PATH=$PATH:/opt/www/cgi-bin    # The Suse location
PATH=$PATH:/srv/www/cgi-bin    # The Suse location
export PATH

# Do the searching

CONFIG_DIR=$wwwoffle_spool/search/htdig/conf
export CONFIG_DIR

htsearch -c search/htdig/conf/htsearch.conf
